window.BASE_STORES = [
  {id:'mw-certosa',chain:'MediaWorld',name:'Milano Certosa',city:'Milano',region:'Lombardia',zone:'Nord Ovest',priority:'A+',opFit:100,comFit:97,top25:true,lat:45.495,lng:9.128,source:'https://www.mediaworld.it/it/store/milano-certosa-2170',notes:'Tech Village / flagship. Forte rilevanza GE e incasso.'},
  {id:'mw-porta-roma',chain:'MediaWorld',name:'Porta di Roma / Bufalotta',city:'Roma',region:'Lazio',zone:'Centro',priority:'A+',opFit:100,comFit:97,top25:true,lat:41.970,lng:12.536,source:'https://www.mediaworld.it/it/store/porta-di-roma-2410',notes:'Tech Village / grande centro commerciale.'},
  {id:'mw-trento',chain:'MediaWorld',name:'Trento',city:'Trento',region:'Trentino-Alto Adige',zone:'Nord Est',priority:'A+',opFit:98,comFit:97,top25:true,lat:46.074,lng:11.121,source:'https://www.mediaworld.it/it/store/trento-2154',notes:'Store baseline: software già utilizzato e misurato.'},
  {id:'mw-lingotto',chain:'MediaWorld',name:'Torino Lingotto',city:'Torino',region:'Piemonte',zone:'Nord Ovest',priority:'A',opFit:96,comFit:97,top25:true,lat:45.035,lng:7.667,source:'https://www.mediaworld.it/it/store/torino-lingotto-2171',notes:'Full store / shopping centre.'},
  {id:'mw-novoli',chain:'MediaWorld',name:'Firenze Novoli',city:'Firenze',region:'Toscana',zone:'Centro',priority:'A',opFit:95,comFit:97,top25:true,lat:43.799,lng:11.218,source:'https://www.mediaworld.it/it/store/firenze-novoli-2180',notes:'Full store / Parco San Donato.'},

  {id:'ue-roncadelle',chain:'Unieuro',name:'Brescia - Roncadelle',city:'Roncadelle',region:'Lombardia',zone:'Nord Ovest',priority:'A',opFit:92,comFit:91,top25:true,lat:45.527,lng:10.154,source:'https://www.unieuro.it/online/negozi/Unieuro-Brescia---Roncadelle',notes:'Direct / grande area retail.'},
  {id:'ue-parma',chain:'Unieuro',name:'Parma - Torri',city:'Parma',region:'Emilia-Romagna',zone:'Nord Est',priority:'A',opFit:91,comFit:91,top25:true,lat:44.801,lng:10.328,source:'https://www.unieuro.it/online/negozi',notes:'Direct / Centro Torri.'},
  {id:'ue-moncalieri',chain:'Unieuro',name:'Moncalieri',city:'Moncalieri',region:'Piemonte',zone:'Nord Ovest',priority:'A-',opFit:91,comFit:91,top25:true,lat:45.000,lng:7.682,source:'https://www.unieuro.it/online/negozi',notes:'Direct / retail zone.'},
  {id:'ue-bologna-lame',chain:'Unieuro',name:'Bologna - Lame',city:'Bologna',region:'Emilia-Romagna',zone:'Nord Est',priority:'A',opFit:90,comFit:91,top25:true,lat:44.521,lng:11.326,source:'https://www.unieuro.it/online/negozi',notes:'Direct / shopping-centre context.'},
  {id:'ue-mestre',chain:'Unieuro',name:'Mestre - via Don Tosatto',city:'Mestre',region:'Veneto',zone:'Nord Est',priority:'A',opFit:90,comFit:91,top25:true,lat:45.490,lng:12.240,source:'https://www.unieuro.it/online/negozi',notes:'Direct / grande bacino commerciale.'},

  {id:'co-carpi',chain:'Comet',name:'Carpi',city:'Carpi',region:'Emilia-Romagna',zone:'Nord Est',priority:'A+',opFit:94,comFit:68,top25:true,lat:44.783,lng:10.885,source:'https://www.comet.it/negozi/emilia-romagna/modena/comet-carpi',notes:'Pagina store: Piccoli e Grandi elettrodomestici.'},
  {id:'co-casalecchio',chain:'Comet',name:'Casalecchio',city:'Casalecchio di Reno',region:'Emilia-Romagna',zone:'Nord Est',priority:'A+',opFit:94,comFit:68,top25:true,lat:44.475,lng:11.277,source:'https://www.comet.it/negozi/emilia-romagna/bologna/comet-casalecchio',notes:'Full consumer + materiale elettrico.'},
  {id:'co-castelguelfo',chain:'Comet',name:'Castel Guelfo',city:'Castel Guelfo',region:'Emilia-Romagna',zone:'Nord Est',priority:'A+',opFit:94,comFit:68,top25:true,lat:44.432,lng:11.680,source:'https://www.comet.it/negozi/emilia-romagna/bologna/comet-castel-guelfo',notes:'Retail park / forte segnale GE.'},
  {id:'co-fidenza',chain:'Comet',name:'Fidenza',city:'Fidenza',region:'Emilia-Romagna',zone:'Nord Est',priority:'A+',opFit:94,comFit:68,top25:true,lat:44.866,lng:10.060,source:'https://www.comet.it/negozi/emilia-romagna/parma/comet-fidenza',notes:'Adiacente Fidenza Village; GE esplicito.'},
  {id:'co-verona',chain:'Comet',name:'Verona c.c. Grande Mela',city:'Lugagnano di Sona',region:'Veneto',zone:'Nord Est',priority:'A+',opFit:94,comFit:68,top25:true,lat:45.430,lng:10.820,source:'https://www.comet.it/negozi/veneto/verona/comet-verona-grande-mela',notes:'Shopping centre / GE esplicito.'},

  {id:'eu-mondovi',chain:'Euronics',name:'Mondovì',city:'Mondovì',region:'Piemonte',zone:'Nord Ovest',priority:'A+',opFit:95,comFit:65,top25:true,lat:44.389,lng:7.821,source:'https://www.euronics.it/store?storeId=8033695243614',notes:'Catalogo dedicato Grandi Elettrodomestici.'},
  {id:'eu-torino-romania',chain:'Euronics',name:'Torino Corso Romania',city:'Torino',region:'Piemonte',zone:'Nord Ovest',priority:'A+',opFit:95,comFit:65,top25:true,lat:45.110,lng:7.730,source:'https://www.euronics.it/store?storeId=8058669661690',notes:'Catalogo GE dedicato.'},
  {id:'eu-venaria',chain:'Euronics',name:'Venaria Reale',city:'Venaria Reale',region:'Piemonte',zone:'Nord Ovest',priority:'A+',opFit:95,comFit:65,top25:true,lat:45.132,lng:7.632,source:'https://www.euronics.it/store?storeId=8058669661799',notes:'Full store / shopping centre / GE dedicato.'},
  {id:'eu-elmas',chain:'Euronics',name:'Cagliari - Elmas',city:'Elmas',region:'Sardegna',zone:'Isole',priority:'A+',opFit:93,comFit:65,top25:true,lat:39.267,lng:9.051,source:'https://www.euronics.it/store?storeId=8058669661898',notes:'Catalogo GE dedicato.'},
  {id:'eu-torino-nizza',chain:'Euronics',name:'Torino Via Nizza',city:'Torino',region:'Piemonte',zone:'Nord Ovest',priority:'A+',opFit:90,comFit:65,top25:true,lat:45.056,lng:7.678,source:'https://www.euronics.it/store?storeId=8033695242952',notes:'Urban full-store / GE dedicato.'},

  {id:'tr-collegno',chain:'Trony',name:'Collegno',city:'Collegno',region:'Piemonte',zone:'Nord Ovest',priority:'A+',opFit:86,comFit:52,top25:true,lat:45.077,lng:7.573,source:'https://www.trony.it/collegno-TRO402/',notes:'Pagina store espone GE e categorie incasso.'},
  {id:'tr-sesto',chain:'Trony',name:'Sesto San Giovanni',city:'Sesto San Giovanni',region:'Lombardia',zone:'Nord Ovest',priority:'A+',opFit:86,comFit:52,top25:true,lat:45.534,lng:9.235,source:'https://www.trony.it/sesto-san-giovanni-TRO459/',notes:'GE + incasso dettagliato.'},
  {id:'tr-roma',chain:'Trony',name:'Roma - Via B. Alimena',city:'Roma',region:'Lazio',zone:'Centro',priority:'A+',opFit:84,comFit:52,top25:true,lat:41.860,lng:12.620,source:'https://www.trony.it/ROMA-TRO511',notes:'Grande bacino metropolitano; GE/incasso.'},
  {id:'tr-bologna',chain:'Trony',name:'Bologna',city:'Bologna',region:'Emilia-Romagna',zone:'Nord Est',priority:'A',opFit:82,comFit:52,top25:true,lat:44.494,lng:11.342,source:'https://www.trony.it/bologna-TRO450/',notes:'Pagina store ufficiale.'},
  {id:'tr-pomezia',chain:'Trony',name:'Pomezia',city:'Pomezia',region:'Lazio',zone:'Centro',priority:'A',opFit:82,comFit:52,top25:true,lat:41.669,lng:12.501,source:'https://www.trony.it/pomezia-TRO499/',notes:'Bacino retail suburbano.'}
];
